     
<script type="text/javascript">
 
 
</script>
     
      
      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Metropoli</h1>
        <p class="lead">Comienza a disfrutar al máximo de las promociones e importantes ahorros que te ofrece tu membresía durante tus compras cotidianas y disfruta los beneficios que nuestros establecimientos previamente seleccionados han diseñado especialmente para ti al pertenecer al Club más exclusivo</p>
        <a data-toggle="modal" href="#myModal" class="btn btn-success btn-large">Registrarse!</a>
       </div>

      <hr>

      <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details »</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details »</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn" href="#">View details »</a></p>
        </div>
      </div>

  <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Registro de Cliente</h3>
  </div>
  <div class="modal-body">
   <form class="form-horizontal">
     <div class="control-group">
    <label class="control-label" for="inputEmail">Numero de Tarjeta</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Tarjeta">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">
      <input type="password" id="inputPassword" placeholder="Password">
    </div>
  </div>
 
  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    <button class="btn btn-primary">Guardar</button>
  </div>
  </form>
  
</div>