 

<div class="container content">
    	<div class="row tryNowTeaser">
        	<div class="span9">
            	<h2>	<p>View script for controller <b>About</b> and script/action name <b>index</b></p>
            	</h2>
                <h4>Smart App can help you run your business smartly. Here's how.</h4>
            </div>
            <div class="span3">
            	<a href="#" class="btn btn-large btn-warning pull-right btnTryNow">Try Smart App!</a>
            </div>
        </div>
        <hr>
        <div class="row tourCnt">        	
        	<div class="span3">
            	<div class="tabbable tabs-left">
                    <ul class="nav nav-tabs span3">
                      <li class="active"><a href="#FH" data-toggle="tab">Feature Highlights</a></li>
                      <li class=""><a href="#FFL" data-toggle="tab">Full Feature List</a></li>
                      <li class=""><a href="#SAS" data-toggle="tab">Smart App Showcase</a></li>	
                    </ul>                    
                  </div>
            </div>
            <div class="span9">
            	<div class="tab-content">
                  <div class="tab-pane active" id="FH">
                  	<div class="row">      
                    	<div class="span9">
                        	<h2>Feature Highlights</h2>              	
                        </div>                    	
                    	<div class="span5">                        	
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        	<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                        </div>
                        <div class="span4">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/360x200" alt=""></a>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>  
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>  
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                            <h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                            <a href="#" class="btn btn-success">Learn more</a>
                        </div>
                    </div>
                    <div class="row plansTeaser">
                    	<div class="span9">
                        	<div class="alert alert-success">
                            	<p>If you saw all of these features, then you must be really ready to try Smart App.</p>
                                <p><a href="#" class="btn btn-large btn-warning"><strong>See Plans &amp; Pricing</strong></a></p>                                
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="tab-pane" id="FFL">
                    <div class="row">      
                    	<div class="span9">
                        	<h2>Full Feature List</h2>              	
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div> 
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>                                           	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div> 
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>                                           	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div> 
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>                                           	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">      
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x130" alt=""></a>
                        </div> 
                    	<div class="span6">
                        	<h3>Feature Heading</h3>  
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                        </div>                                           	
                    </div>
                    <div class="row plansTeaser">
                    	<div class="span9">
                        	<div class="alert alert-success">
                            	<p><strong>Sign up now, it takes less than a minute and it's free.</strong></p>
                                <p><a href="#" class="btn btn-large btn-warning"><strong>Get an account now!</strong></a></p>                                
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="tab-pane showcaseCnt" id="SAS">
                    <div class="row">      
                    	<div class="span9">
                        	<h2>Smart App Showcase</h2>              	
                            <p class="shortDesc">Smart App is very flexible and easy to customize. Please take a look at our showcase.</p>
                        </div>                    	
                    </div>
                    <hr>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                    </div>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                    </div>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                    </div>
                    <div class="row">
                    	<div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>
                        <div class="span3">
                        	<a href="#" class="thumbnail"><img src="http://placehold.it/260x180" alt=""></a>
                            <p><a href="#">www.setyshowcaseurlhere.com</a></p>                            
                        </div>                        
                    </div>                   
                  </div>
                </div>
            </div>            
    	</div>
        <div class="footer">
        	<div class="row">
            	<div class="span12">
                	<p class="pull-left">© 2012 - ImpressiveApps, All rights reserved.</p>
                    <p class="pull-right"><a href="#">Terms of Use</a> &nbsp;|&nbsp; <a href="#">Privacy Policy</a></p>
                </div>
            </div>
        </div>
    </div>